### ISSUE TITLE
#to_s(:symbol) should print the name if no symbol is defined

### ISSUE THREAD

**Issue by posgarou** [joshwlewis/unitwise#18]
If you run `Unitwise('15', 'teaspoon').to_s(:symbol)`, you get the very unhelpful `"15 1"`.

1. First, I think `'15 tsp'` is a reasonable expectation, but that aside
2. If there is no symbol defined for a unit (as is I think the case here: `Unitwise('15', 'teaspoon').unit.terms[0].atom.symbol # => nil`), it would be great if `#to_s(:symbol)` would default to showing the full name ("1 teaspoon").

Rationale: In my case, I have a list of items.  I want as many of them as possible to render with symbols (e.g., "10 oz").  It's laborious to check, while rendering them, whether there is a symbol defined for the relevant unit.

**Comment by joshwlewis** [comment]
On your first point -- I don't want to override properties defined (or not defined) by [UCUM](http://unitsofmeasure.org). It might not be a bad idea to open an issue there to add teaspoon's symbol.

Though I think you are right on the second. `to_s(:symbol)` should probably fall back to `to_s` when there isn't a symbol.

**Comment by posgarou** [comment]
(1) That makes perfect sense.

(2) That would be great.

**Comment by joshwlewis** [comment]
I just pushed a new version up to fix this (1.1.0). Now `to_s(:symbol)` will fall back to `to_s(:primary_code)` if there isn't a symbol. Looks like there were a few other cases where `secondary_code` wasn't available either, so falling back to `primary_code` (rather than `names`) was the safest bet.

Thanks for reporting this, and sorry for the delay!

**Comment by posgarou** [comment]
Sounds good.  Thanks!
