### ISSUE TITLE
unitwise/ext causing slow performance on the whole application

### ISSUE THREAD

**Issue by vinh0604** [joshwlewis/unitwise#19]
`require unitwise/ext` greatly decrease the performance, which could be observed by this mini benchmark on time initilizing

```
irb > require 'benchmark'
 => true
irb > Benchmark.bmbm {|x| x.report("Report") { 20.times {|i| Time.new 2015, 5, 5 } }}
Rehearsal ------------------------------------------
Report   0.000000   0.000000   0.000000 (  0.000213)
--------------------------------- total: 0.000000sec

             user     system      total        real
Report   0.000000   0.000000   0.000000 (  0.000149)
 => [#<Benchmark::Tms:0x007f9da902b1d0 @label="Report", @real=0.0001490480026404839, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.0, @total=0.0>]

irb > require 'unitwise/ext'
 => true
irb > Benchmark.bmbm {|x| x.report("Report") { 20.times {|i| Time.new 2015, 5, 5 } }}
Rehearsal ------------------------------------------
Report   0.570000   0.010000   0.580000 (  0.585193)
--------------------------------- total: 0.580000sec

             user     system      total        real
Report   0.470000   0.010000   0.480000 (  0.499391)
 => [#<Benchmark::Tms:0x007f9daa2eb888 @label="Report", @real=0.49939128999903915, @cstime=0.0, @cutime=0.0, @stime=0.010000000000000009, @utime=0.47, @total=0.48>]
```
Looking at the code, I guess overriding `method_missing` is the cause of this, so I think it could be better if we completely remove this and change to use `define_method` on proper supported units list.

Cheers.

**Comment by joshwlewis** [comment]
Yeah, I can reproduce this as well. It looks like Time is calling `to_str` on 5, which is not a method, so the `method_missing` fires. I don't really want to use `define_method` here, because there would be way too many methods (thousands) to define.

Aside from the performance issues `require 'unitwise/ext'` is also doing some serious monkey patching. I'm debating changing the README to encourage use of `require 'unitwise'` instead (which I encourage you to do as well). I love the syntax of `10.mile`, but it comes with a price.

**Comment by vinh0604** [comment]
Yeah, I stopped using `require 'unitwise/ext'` now, costing me several days to debug though :smile: 

I agree with you, encouraging use of require 'unitwise' and a usage notice on `require 'unitwise/ext'` in README would help. In the long term, I think it's better if we completely remove this patch.
