### ISSUE TITLE
Converting meters to feet to meters yields floating point inaccuracy

### ISSUE THREAD

**Issue by edave** [joshwlewis/unitwise#35]
Thanks for the awesome gem!

Trying a simple back and forth to assess the accuracy of conversions leads to a small inaccuracy, likely due to floating point errors. For example:
```ruby
ten_meters = Unitwise(10, 'm')
ten_meters_converted_to_feet = ten_meters.to_foot
ten_meters_converted_to_feet.to_f # Returns 32.80839895 ft
ten_meters_converted_to_feet.to_meter.to_f # Returns 9.99999999996 meters, 10 expected
```

Perhaps this is also related to #27?

**Comment by pinkynrg** [comment]
I was actually going for this gem since it seems to be the best there is on the web.

```
Unitwise(1,'circle').convert_to('degree') # Returns 359.9999999999999712, 360 expected
```

**Comment by joshwlewis** [comment]
Hey y'all. Thanks for the report. At first, I was eager to dismiss this as not a real issue due to the `.to_f` calls in the bug report. I've even seen it myself, but dismissed it for the same reason: `Float`s are notoriously susceptible to accuracy loss.

However, I think y'all are right. This case is clearly problematic: 
```
Unitwise(10, 'm').to_foot.to_meter
=> #<Unitwise::Measurement value=9.99999999996 unit=meter>
```

The user has not used a float, but still sees floating point inaccuracy.

I think this issue stems from the fact that Unitwise's unit data gets serialized as `Float`s by the YAML parser, for example, [here](https://github.com/joshwlewis/unitwise/blob/master/data/derived_unit.yaml#L31). I suspect that rebuilding those YAML files with `BigDecimal`s would solve issues like these.

**Comment by joshwlewis** [comment]
These issues were fixed in #45. Upgrade to version 2.2.0 to pick up the changes. Thanks for the report, y'all.

**Comment by edave** [comment]
Awesome, thanks @joshwlewis!

**Comment by pinkynrg** [comment]
Thanks!
