### ISSUE TITLE
Conversion from 'm/s' to 'foot/minute' fails but it works for 'm/s' to 'foot/hour' & 'm/s' to 'foot/second'

### ISSUE THREAD

**Issue by sandeepnagra** [joshwlewis/unitwise#36]
I tried foot/second & foot/hour, they both worked but foot/minute fails.

irb(main):017:0> Unitwise(1, 'm/s').convert_to("foot/second")
=> #<Unitwise::Measurement value=3.280839895 unit=foot/second>

irb(main):018:0> Unitwise(1, 'm/s').convert_to("foot/minute")
Unitwise::ConversionError: Can't convert 1 m/s to foot/minute.
from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/unitwise-2.0.0/lib/unitwise/
measurement.rb:31:in convert_to' from (irb):18 from c:/Ruby22-x64/bin/irb:11:in

'
irb(main):019:0> Unitwise(1, 'm/s').convert_to("foot/hour")
=> #<Unitwise::Measurement value=0.11811023622047244094488222047244E5 unit=foot/hour>

Any idea why just "foot/minute" is failing?

**Comment by sandeepnagra** [comment]
I did more testing and found out that speed conversion are only supported for /second or /hour but not for /minute irrespective of what the distance unit is.

So even if I try to convert m/s to m/minute, it will still fail. Is there any specific reason why /minute is not supported for conversions?

**Comment by joshwlewis** [comment]
Hi @sandeepnagra. Yes, it is a bit weird. The reason it's failing is because there are two units with the name 'minute'. Minute (the plane angle measurement) happens to be higher in the list of units, so it's what gets parsed first. Unitwise tries to be helpful and resolve units by name when it can, but the guaranteed way to ensure you have the right unit is to use it's `primary_code` or `secondary_code`. Those are the official, non-conflicting designations from UCUM. So, while it's less pretty, `Unitwise(1, 'm/s').convert_to("[ft_i]/min")` would be what you'd want to use.

You can find the primary and secondary codes with `Unitwise.search("minute")`, or by looking [here](https://github.com/joshwlewis/unitwise/blob/master/data/derived_unit.yaml#L436-L447).
