### ISSUE TITLE
Why does an ounce unit contain an empty term in root_terms?

### ISSUE THREAD

**Issue by linnea-flexe** [joshwlewis/unitwise#64]
Ounces have a 2nd term in the `root_terms` list, which appears to be effectively null:
![Screen Shot 2019-12-17 at 18 01 04](https://user-images.githubusercontent.com/44380972/71049468-4b444e00-20f7-11ea-884a-45edc31bdbbc.png)

The code I was inspecting when I found this is buggy and should probably be calling `terms` not `root_terms`, but I don't understand why the behavior is different here, or what the intended difference between the two methods is. Can you shed any light? Thanks.

**Comment by joshwlewis** [comment]
Hi, I think this happens because of how the unit is defined here: https://github.com/joshwlewis/unitwise/blob/master/data/derived_unit.yaml#L1930. `[lb_av]/16` has a numerator and denominator and those are the two terms you are seeing. The second term there has a `exponent=-1` to reflect that it's the denominator.
